Repository RitamPaul/Basic_Codes, pull requests merged in 2022-10, with the labels that each got.

#5 Created Langrange InterpolationFormula in C
  Lagrange_Interpolation.c/LANGRANG I.F.c
  Lagrange_Interpolation.c/readme.txt
  Pwd_EncoderDecoder.py/readme.txt
Labels: hacktoberfest, hacktoberfest-accepted

#7 Added a Singly_LinkedList code in cli mode
  Singly_LinkedList/SingleLL_DSA.c
  Singly_LinkedList/readme.txt
Labels: good first issue

#13 Add files via upload
  Searching Algorithms/binary_search.cpp
  Searching Algorithms/linear-search.cpp
Labels: good first issue

#18 quickshort in c
  quicksort.c
Labels: hacktoberfest, hacktoberfest-accepted

#16 quick sort in c
  quicksort.c
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#15 Create flatten_multilevel_doubly_ll.cpp
  Doubly_Linked_List.c/flatten_multilevel_doubly_ll.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#12 stack and queue using structure
  QUEUE_using_Structure.c
  STACK_using_Structure.c
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#4 Added Binary Search implementation in C++
  Array_FundamentalOperations/BinarySearch.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#3 remove_punctuation added
  remove_punctuation.py
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#23 Searching_Algo_in_Graph
  Searching_Algorithm_in_C/BFS.c
  Searching_Algorithm_in_C/DFS.c
  Searching_Algorithm_in_C/README.md
Labels: hacktoberfest, hacktoberfest-accepted

#24 Finding the beginning node in a circular linked list
  Beginning_Node_of_Circular_LinkedList/Beginning_Node_of_Circular_LL.c
  Beginning_Node_of_Circular_LinkedList/README.txt
Labels: good first issue

#27 LevelWisePrintOfTree.cpp
  LevelWisePrintOfTree.cpp
Labels: good first issue
